from shared_config import DEFAULT_ADS_JSONL, DEFAULT_INDEX_DIR, REPO_ROOT

EMBEDDING_MODEL_NAME = "BAAI/bge-m3"
DEFAULT_TOP_K = 5
ENCODE_BATCH_SIZE = 32
INDEX_FILENAME = "index.faiss"
ADS_SIDECAR_FILENAME = "ads.json"

