from pathlib import Path

from generation.config import DEFAULT_OUTPUT_CSV, DEFAULT_PLACED_ADS_CSV
from lmarena_prep.config import AD_GPU_MEMORY_UTILIZATION, AD_MODEL_NAME

REPO_ROOT = Path(__file__).resolve().parents[1]

DEFAULT_POSITIONS_CSV = DEFAULT_PLACED_ADS_CSV
DEFAULT_ADS_CSV = DEFAULT_OUTPUT_CSV
DEFAULT_SCORES_CSV = REPO_ROOT / "data/processed/placement_testing/placement_scores.csv"

JUDGE_MODEL_NAME = AD_MODEL_NAME
JUDGE_MAX_MODEL_LEN = 16384
JUDGE_MAX_TOKENS = 256
JUDGE_GPU_MEMORY_UTILIZATION = AD_GPU_MEMORY_UTILIZATION
JUDGE_BATCH_SIZE = 32
CHECKPOINT_EVERY = 1000
AD_SLOT = "[ad slot]"
